Create Assignment_1.cu
IEEE-NITK/SummerProjects20 pull request #11
Opened 2020-04-23 08:11 UTC by tharun634

2020-04-23 08:39 UTC, ameyanrd requested changes
Hi! Please make the changes, compile your program and push the changes.

2020-04-23 08:39 UTC, ameyanrd commented on Assignment_1.cu
> +    float h_in1[Array_Size],h_in2[Array_Size] h_out[Array_Size];
float h_in1[Array_Size],h_in2[Array_Size], h_out[Array_Size]; // You forgot the comma after h_in2.

2020-04-23 08:40 UTC, ameyanrd commented on Assignment_1.cu
> +     d_out[i] = d1_in[i] + d2_in[i];
error: identifier "i" is undefined
error: identifier "d1_in" is undefined
error: identifier "d2_in" is undefined

2020-04-23 13:54 UTC, ameyanrd approved these changes
Great!

2020-04-24 10:17 UTC, niranjansy approved these changes

2020-04-24 10:18 UTC, merged