Assignment 1 added
IEEE-NITK/SummerProjects20 pull request #5
Opened 2020-04-22 14:28 UTC by DeltaCube23

I have added the 1st assignment, please notify me if any changes are required.

2020-04-22 14:50 UTC, ameyanrd requested changes
Small change required.

2020-04-22 14:50 UTC, ameyanrd commented on 96447859_adithya/array_sum.cu
> +    }
Generate your input arrays for big Array_size.

2020-04-23 17:14 UTC, DeltaCube23 commented
I fixed inputs so that it can generate for large numbers

2020-04-24 10:31 UTC, niranjansy approved these changes

2020-04-24 10:31 UTC, merged