Sum2Arrays
IEEE-NITK/SummerProjects20 pull request #6
Opened 2020-04-22 16:10 UTC by amal-majunu

2020-04-22 16:30 UTC, ameyanrd requested changes

2020-04-22 16:30 UTC, ameyanrd commented on Assignment1
> +    int Array_Bytes = Array_Size * sizeof(int);
Hi! You didn't write the code for setting h1_in and h2_in. You can set them randomly (using rand()) or h1_in[i] = i, h2_in[i] = 2*i (whatever logic you want). Also, Array_Size being a global variable is 0. The aim is to use GPU for large number of inputs.

2020-04-23 16:45 UTC, amal-majunu commented
Made the following changes.

2020-04-23 18:22 UTC, niranjansy approved these changes

2020-04-23 18:22 UTC, niranjansy commented on Assignment1
> +    int h1_in[Array_Size], h_out[Array_Size],h2_in[Array_Size];
You haven't initialized Array_Size. Either give it a value in its global declaration or take input from the user.

2020-04-24 10:29 UTC, merged